---
- hosts: jenkins
  vars:
    - jenkins_hostname: jenkins.dev
    - jenkins_http_port: 8080

  roles:
    - role: geerlingguy.java
      become: true
    - role: geerlingguy.jenkins
      become: true