---
- hosts: all
  become: true

  vars:
    - app_path: /home/vagrant/continous-delivery-training/
    - nodejs_version: "6.x"

  pre_tasks:
    - name: Update apt cache if needed.
      apt: update_cache=yes cache_valid_time=3600

  roles:
    - geerlingguy.git
    - geerlingguy.nodejs

  tasks:
    - git:  repo=https://github.com/lucasmonteiro001/continous-delivery-training.git
            dest={{ app_path }}
    
    - name: Install packages from package.json
      npm: path={{ app_path }}

    - name: Build application
      command: >
        npm run build
        chdir={{ app_path }}

    - name: Install "pm2" node.js package globally.
      npm:
        name: pm2
        global: yes

    - name: Start application 
      command: >
        npm run start:prod
        chdir={{ app_path }}
