---
- hosts: all
  become: yes

  pre_tasks:
    - name: Update apt cache if needed.
      become: yes
      apt: update_cache=yes cache_valid_time=3600

  vars:
    - app_path: /home/{{ ansible_ssh_user }}/continous-delivery-training/
    - nodejs_npm_global_packages: ["pm2"]
    - nodejs_version: "6.x"

  roles:
    - geerlingguy.nodejs

  tasks:
    - apt_repository:
        repo: 'ppa:fkrull/deadsnakes'

    - name: Install python3.6
      apt: name=python3.6 state=present



- hosts: all
  vars:
    - app_path: /home/{{ ansible_ssh_user }}/continous-delivery-training/

  tasks:
    - name: Copy build files to remote
      copy:
        src: ../../build/
        dest: "{{ app_path }}"

    - name: Start application 
      raw: "cd {{ app_path }} && /usr/local/lib/npm/bin/pm2 start /usr/bin/python3.6 -- -m http.server 59999"
      
