---
- hosts: maonamassa
  vars:
    - app_path: /home/{{ ansible_ssh_user }}/continous-delivery-training/
    - pm2_exec: /usr/local/lib/npm/bin/pm2
    - python_exec: /usr/bin/python3.6
    - service_name: "{{ ansible_ssh_user }}.continuous-delivery.service"

  tasks:
    - template:
        src: ../templates/service.j2
        dest: /etc/systemd/system/{{ service_name }}
        owner: "{{ ansible_ssh_user }}"
        mode: 0755
      become: true

    - name: Copy exec file to remote
      copy: 
        src: ../startup
        dest: "{{ app_path }}"
        mode: 0755

    - name: Copy build files to remote
      copy:
        src: ../../build/
        dest: "{{ app_path }}"

    - service:
        name: "{{ service_name }}"
        state: started
        enabled: true
      become: true